name: talkie
description: "Talkie - Language learning app with speech recognition and translation"
publish_to: 'none'

version: 1.4.0+18

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.0
  
  # Speech Recognition (STT)
  speech_to_text: ^7.0.0
  
  # Text-to-Speech (TTS)
  flutter_tts: ^4.2.0
  audio_session: ^0.1.21
  
  # Translation API
  http: ^1.6.0
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  
  # File Picker
  file_picker: ^8.1.4
  
  # Permissions
  permission_handler: ^11.3.0
  tutorial_coach_mark: ^1.3.3
  sqflite_common_ffi: ^2.4.0+2
  sqlite3_flutter_libs: ^0.5.18
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.4
  google_mobile_ads: ^7.0.0
  url_launcher: ^6.3.1
  supabase_flutter: ^2.12.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  workmanager: ^0.9.0+3
  uuid: ^4.5.2
  sqflite_common_ffi_web: ^1.1.1
  connectivity_plus: ^7.0.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.10.0


dev_dependencies:
  build_runner: ^2.11.1
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Generate localization code from ARB files
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/help/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
